# Generated by Django 3.0.7 on 2021-01-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joinyear',
            field=models.TextField(default='2021'),
        ),
    ]
